resources:
  source_lang_model: /home/marina/Workspace/data/toy_resources_data_cleaning/lm.tok.en
  target_lang_model: /home/marina/Workspace/data/toy_resources_data_cleaning/lm.tok.de
features:
  - name: length_ratio_source_target
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: both
    logic: len(input[0]) / len(input[1]) if len(input[1]) else 0
  - name: length_ratio_target_source
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: both
    logic: len(input[1]) / len(input[0]) if len(input[0]) else 0
  - name: length_absolute_difference
    type: simple
    units: [words,numbers,alphanums,punctuation,".",",",":",";","!","?"]
    applies_to: both
    logic: abs(len(input[0]) - len(input[1]))
  - name: length_relative_difference
    type: simple
    units: [words,numbers,alphanums,punctuation,".",",",":",";","!","?"]
    applies_to: both
    logic: abs(len(input[0]) - len(input[1])) / (max(len(input[0]), len(input[1]))) if (max(len(input[0]), len(input[1]))) else 0
  - name: length
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: source
    logic: len(input[0])
  - name: length
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: target
    logic: len(input[1])
  - name: language_model_probability
    type: external
    units: [sentence]
    applies_to: source
    logic: model.score(input[0], side)
    resource: language_model
  - name: language_model_probability
    type: external
    units: [sentence]
    applies_to: target
    logic: model.score(input[1], side)
    resource: language_model
  - name: language_model_perplexity
    type: external
    units: [sentence]
    applies_to: source
    logic: model.perplexity(input[0], side)
    resource: language_model
  - name: language_model_perplexity
    type: external
    units: [sentence]
    applies_to: target
    logic: model.perplexity(input[1], side)
    resource: language_model
