resources:
  source_language_model: /home/marina/Workspace/data/toy_resources_data_cleaning/lm.tok.de
  target_language_model: /home/marina/Workspace/data/toy_resources_data_cleaning/lm.tok.en
  source_lexical_table: /home/marina/Workspace/data/toy_resources_data_cleaning/lex.deen
  target_lexical_table: /home/marina/Workspace/data/toy_resources_data_cleaning/lex.ende
features:
  - name: counts_difference
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: []
    logic: [ratio,inverse_ratio,difference,difference_normalized]
  - name: counts_difference
    type: simple
    units: [".",",",":",";","!","?"]
    applies_to: []
    logic: [difference,difference_normalized]
  - name: counts
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: [source,target]
    logic: [count]
  - name: jaccard
    type: simple
    units: [words,numbers,alphanums,punctuation]
    applies_to: []
    logic: [jaccard_index]
  - name: language_model_probability
    type: complex
    units: [sentence]
    applies_to: [source,target]
    resource: language_model
    class: LanguageModelProbability
  - name: language_model_perplexity
    type: complex
    units: [sentence]
    applies_to: [source,target]
    resource: language_model
    class: LanguageModelPerplexity
  - name: lexical_probability
    type: complex
    units: [words]
    applies_to: [source,target]
    resource: lexical_table
    class: LexicalProbability
